### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [ryotakato/docker-for-qiskit#1]
I recently came across your project docker-for-qiskit and I noticed that the repository github.com/ryotakato/docker-for-qiskit currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by ryotakato** [comment]
Hi Juan,

Thank you for checking my repository.
When I created this repository, I was mean to only use for my learning. So I haven't thought deeply.
But your advise is certainly right.

Now I have added MIT LICENSE at 825c47435bc7ca7ed135803b8dd954681f951f97.
Please confirm.

And, this question which is from my curious,
Is this issue related to your job ?
I am worried whether I maybe make mistake about this repository, because I saw your account show you are at IBM Quamtum.  
In particular how to use qiskit.

**Comment by cbjuan** [comment]
Thank you!
